services:

  broker:
    build:
      context: ./services/broker
      dockerfile: ${DOCKERFILE_SERVICE}
      args:
        GO_MAIN: "/src/cmd/api"
      network: host
    container_name: broker
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - micro-net
      - db-net
    depends_on:
      - postgres

  authentication:
    build:
      context: ./services/authentication
      dockerfile: ${DOCKERFILE_SERVICE}
      args:
        GO_MAIN: "/src/cmd/api"
      network: host
    container_name: auth
    restart: always
    environment:
      DSN: "host=postgres port=${DB_PORT} user=${DB_USER} password=${DB_PASS} dbname=${DB_NAME} sslmode=disable timezone=UTC connect_timeout=5"
    networks:
      - micro-net
      - db-net
    depends_on:
      - broker

  clientmq:
    build:
      context: ./services/clientmq
      dockerfile: ${DOCKERFILE_SERVICE}
      args:
        GO_MAIN: "/src"
      network: host
    container_name: clientmq
    restart: always
    networks:
      - micro-net
      - db-net
      - mq-net
    depends_on:
      - broker
      - rabbitMQ

  front-end:
    build:
      context: ./services/front-end
      dockerfile: ${DOCKERFILE_SERVICE}
      args:
        GO_MAIN: "/src/cmd/web"
      network: host
    container_name: frontend
    restart: always
    volumes:
      - "./services/front-end/src/cmd/web/templates:/templates:ro"
    ports:
      - "${FRONT_PORT}:8080"
    networks:
      - micro-net
    depends_on:
      - broker

  rabbitMQ:
    image: 'rabbitmq:3.9-alpine'
    ports:
      - "5672:5672"
    container_name: rabbitMQ
    restart: always
    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq:rw"
    networks:
      - mq-net

  postgres:
    build:
      context: ./db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - "auth:/var/lib/postgresql/data:rw"
    healthcheck:
      test: /postgres.sh
      interval: "5s"
    ports:
      - ${DB_HOST}:${DB_PORT}
    networks:
      - db-net

  logger:
    build:
      context: ./services/logger
      dockerfile: ${DOCKERFILE_SERVICE}
      args:
        GO_MAIN: "/src/cmd/api"
        BUILD_ARGS: ""
      network: host
    container_name: logger
    restart: always
    networks:
      - micro-net
      - log-net
    depends_on:
      - broker
      - mongo

  mongo:
    image: 'mongo:4.2.16-bionic'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - "log:/data/db:rw"
    networks:
      - log-net


volumes:
  auth:
  log:
  rabbitmq-data:


networks:
  db-net:
  micro-net:
  log-net:
  mq-net:
